### ISSUE TITLE
Handle EPIPE

### ISSUE THREAD

**Issue by jhermsmeier** [jhermsmeier/hxd#1]
Handle `Error: write EPIPE` when used with pagers etc.

```
004210b0  00 00 00 10 00 00 02 27 2f 63 6c 6f 63 6b 73 2f  | .......'/clocks/ |
^C
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
```

**Comment by jhermsmeier** [comment]
Fixed in 2c9bd3eab61f0f7e591a2ff902fc8d36928185a7
